@baseUrl = http://localhost:8080/api

### Crear cuenta
POST {{baseUrl}}/cuentas
content-type: application/json

{
    "nombre": "Juan Perez",
    "saldo": 1000
}

### Crear cuenta
POST {{baseUrl}}/cuentas
content-type: application/json

{
    "nombre": "Carlos Lopez",
    "saldo": 150
}

### Listar todo
GET {{baseUrl}}/cuentas
content-type: application/json

### Listar todo
GET {{baseUrl}}/cuentas/saldo
content-type: application/json

{
    "nombre": "Juan Perez"
}

### Listar todo
GET {{baseUrl}}/cuentas/saldo
content-type: application/json

{
    "nombre": "Carlos Lopez"
}

### Crear transacción
POST {{baseUrl}}/transacciones
content-type: application/json

{
    "cuenta_origen_id": 1,
    "cuenta_destino_id": 2,
    "monto": 50,
    "comision": 1.5,
    "tipo": "TRANSFERENCIA",
    "descripcion": "Pago de servicios"
}